configurations:
  '3_8':
    casts:
    - castto: Q4_K_S
      layers: 0-2, 4, 48-54
    - castto: Q3_K_S
      layers: 3, 5-47, 55-56
    gb: --gb 17.0
    notes: Added using --gb 17.0 --q all
  '5_1':
    casts:
    - castto: Q4_1
      layers: 0-56
    notes: full Q4_1 quantization. No patches
  '5_3':
    casts:
    - castto: Q5_1
      layers: 0-2, 4, 6, 8-9, 11-13, 49-54
    - castto: Q4_1
      layers: 3, 5, 7, 10, 14, 16-29, 32-33, 42, 44-48, 55-56
    - castto: Q3_K_S
      layers: 15, 30-31, 34-41, 43
    notes: pretty small
  '5_9':
    casts:
    - castto: Q5_1
      layers: 0-25, 27-28, 44-54
    - castto: Q4_1
      layers: 26, 29-43, 55-56
    notes: should work on 12GB card.
  '6_6':
    casts:
    - castto: BF16
      layers: 0-1
    - castto: Q5_1
      layers: 2-6, 8-11, 13-25, 27-28, 44-54
    - castto: Q8_0
      layers: 7, 12
    - castto: Q4_1
      layers: 26, 29-43, 55-56
    gb: --gb 13
    notes: Comfortable on 12 GB cards
  '6_9':
    casts:
    - castto: BF16
      layers: 0-1
    - castto: Q5_1
      layers: 2-4, 6, 8-9, 11, 13-30, 33, 43-55
    - castto: Q8_0
      layers: 5, 7, 10, 12
    - castto: Q4_1
      layers: 31-32, 34-42, 56
    gb: --gb 12.5
    notes: Good choice for 12GB cards
  '7_3':
    casts:
    - castto: BF16
      layers: 0-3
    - castto: Q6_K
      layers: 4-11, 13-20, 50-54
    - castto: Q8_0
      layers: '12'
    - castto: Q5_K_S
      layers: 21-33, 43-49, 55
    - castto: Q4_K_S
      layers: 34-42
    - castto: Q4_1
      layers: '56'
    notes: Aiming for 12GB cards
  '7_4':
    casts:
    - castto: BF16
      layers: 0-2
    - castto: Q8_0
      layers: 5, 7-12
    - castto: Q5_1
      layers: 3-4, 6, 13-33, 42-55
    - castto: Q4_1
      layers: 34-41, 56
    gb: --gb 12
    notes: roughly same size as 8bit model.
  '7_6':
    casts:
    - castto: BF16
      layers: 0-3, 10
    - castto: Q6_K
      layers: 4-9, 11, 13-20, 50-54
    - castto: Q8_0
      layers: 12
    - castto: Q5_K_S
      layers: 21-33, 43-49, 55
    - castto: Q4_K_S
      layers: 34-42
    - castto: Q4_1
      layers: 56
    notes: Too big for 12GB cards
  '8_2':
    casts:
    - castto: BF16
      layers: 0-4, 7, 10
    - castto: Q6_K
      layers: 5-6, 8-9, 11, 13-21, 50-54
    - castto: Q8_0
      layers: '12'
    - castto: Q5_K_S
      layers: 22-33, 42-49, 55
    - castto: Q4_K_S
      layers: 34-41
    - castto: Q4_1
      layers: '56'
    gb: --gb 11.0
    notes: Added using --gb 11.0 --q all
  '8_4':
    casts:
    - castto: BF16
      layers: 0-4, 10
    - castto: Q8_0
      layers: 5-9, 11-14
    - castto: Q5_1
      layers: 15-35, 41-55
    - castto: Q4_1
      layers: 36-40, 56
    notes: comfortable for 16GB card.
  '8_6':
    casts:
    - castto: BF16
      layers: 0-4, 6-7, 10, 12
    - castto: Q6_K
      layers: 5, 8-9, 11, 13-21, 50-54
    - castto: Q5_K_S
      layers: 22-33, 41-49, 55
    - castto: Q4_K_S
      layers: 34-40
    - castto: Q4_1
      layers: '56'
    gb: --gb 10.0
    notes: Added using --gb 10.0 --q all
  '9_2':
    casts:
    - castto: BF16
      layers: 0-8, 10, 12
    - castto: Q6_K
      layers: 9, 11, 13-21, 49-54
    - castto: Q5_K_S
      layers: 22-34, 41-48, 55
    - castto: Q4_K_S
      layers: 35-40
    - castto: Q4_1
      layers: '56'
    notes: Best for 16GB cards
  '9_6':
    casts:
    - castto: BF16
      layers: 0-10
    - castto: Q8_0
      layers: 11-14, 54
    - castto: Q5_1
      layers: 15-36, 39-53, 55
    - castto: Q4_1
      layers: 37-38, 56
    notes: might just fit on a 16GB card.
metadata:
  native: Q4_1,Q5_1,Q8_0,BF16,F32
